theme: jekyll-theme-minimal
title: Team KnockOut this ProJect!
email: paulamg@uchicago.edu
email: oliverz@uchicago.edu
email: linj24@uchicago.edu
email: keithheinz@uchicago.edu
description: Code Autocomplete Tester
author: Paula, Oliver, Keith, Jason
